input {
  file {
    path => "/usr/share/logstash/logs/anlao-api-json.log"
    start_position => "beginning"
    sincedb_path => "/dev/null" # Chỉ dùng cho thử nghiệm để luôn đọc lại log từ đầu khi restart Logstash
    codec => "json"
  }
}

filter {
  # Bạn có thể lọc hoặc biến đổi trường dữ liệu tại đây nếu cần
  if [level] == "WARN" and "[SECURITY_AUDIT]" in [message] {
    mutate {
      add_tag => [ "security_alert" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "anlao-logs-%{+YYYY.MM.dd}"
  }
  # In log ra console của Logstash để theo dõi thời gian thực
  stdout {
    codec => rubydebug
  }
}
